# +--------------------------------+
# |                                |
# |            LANGUAGE            |
# |                                |
# +--------------------------------+

# The language tag. For it to work, you must create a file called "Messages_<tag>.properties" in the "language" folder.
# The tag is the language tag: "en" for english, "de" for german and so on.
# After you created the file and translated it, you need to enter your tag below.
language: "en"


# +--------------------------------+
# |                                |
# |           WING DISPLAY         |
# |                                |
# +--------------------------------+

# The delay between updating the wings for the player
wing_display_delay: 1s


# +--------------------------------+
# |                                |
# |              EQUIP             |
# |                                |
# +--------------------------------+

# If true, wings the player doesn't have peermission for will be shown too
show_wings_without_permission: false


# +--------------------------------+
# |                                |
# |           PERMISISONS          |
# |                                |
# +--------------------------------+

# Here are all permissions of that plugin listed. You can change them here, if you want:
permissions:
  commands:
    help: "imagewings.help"
    main: "imagewings.main"
    edit: "imagewings.edit"
    equip: "imagewings.equip"
    generate_template: "imagewings.generate.template"
